[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "python -m venv --copies venv",
    ". venv/bin/activate && pip install --upgrade pip",
    ". venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = ". venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"
