[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "python3 -m venv venv",
    "source venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'Build complete'"]

[start]
cmd = "source venv/bin/activate && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
